### ISSUE TITLE
Inconsistently seeing this error

### ISSUE THREAD

**Issue by pb66** [emoncms/app#102] opened 2019-08-16 18:08 UTC
![image](https://user-images.githubusercontent.com/5606042/63187996-20b68b80-c058-11e9-903b-b87afd93caa7.png)

It isn't occurring with any noticeable consistentcy and I'm not sure where it is pointing to. the app_view.php file doesn't have 735 lines! 

All latest versions of master branches as of today.

I'll post more if/when I can.

**Comment by glynhudson** [comment] 2019-08-29 14:39
I cannot seem to recreate that error on MySolar PV / MyEnergy app. However, I'm getting a similar error from the Cos Comparison app 

![Uploading Selection_233.jpg…]()

Looks like duplicate of https://github.com/emoncms/app/issues/62

**Comment by glynhudson** [comment] 2019-08-29 15:14
Another user has reported this error:

![Uploading fa5fa96ea078e37ab10cafefe13a702218d611df.png…]()

https://community.openenergymonitor.org/t/my-app/11800

**Comment by pb66** [comment] 2019-08-30 21:45
I've only seen this occur on my electric apps so a fix to the openevse app cannot possibly fix the issue I've experienced so  this should not be closed

**Comment by glynhudson** [comment] 2019-09-04 22:24
Ok, I've also just experienced this error when trying to create a new MyElectric 1 graph:

![Screenshot 2019-09-04 at 23 20 36](https://user-images.githubusercontent.com/758844/64296126-1dcdfd00-cf6b-11e9-9087-f8716d0d04c2.png)

**Comment by pb66** [comment] 2019-09-05 20:26
Also see https://community.openenergymonitor.org/t/my-electric-app-error-on-session-expiry/11855?u=pb66

**Comment by pb66** [comment] 2019-09-05 20:29
> Ok, I've also just experienced this error when trying to create a new MyElectric 1 graph:
> 
> ![Screenshot 2019-09-04 at 23 20 36](https://user-images.githubusercontent.com/758844/64296126-1dcdfd00-cf6b-11e9-9087-f8716d0d04c2.png)

Although maybe related, the fault reported in your notification is slightly different and I experienced the issue on existing apps rather than when creating new.

**Comment by glynhudson** [comment] 2019-10-24 22:11
![Screenshot 2019-10-24 at 23 10 53](https://user-images.githubusercontent.com/758844/67529264-8b68f080-f6b3-11e9-8c32-3df41f0f3b5e.png)
![Screenshot 2019-10-24 at 23 10 08](https://user-images.githubusercontent.com/758844/67529265-8b68f080-f6b3-11e9-9979-a8197be1142c.png)

**Comment by thedumbterminal** [comment] 2020-01-01 10:34
I'm experiencing this when the device i'm using to display the graph gets disconnected from its wifi. I've created the pull request above to fix this.

**Comment by thedumbterminal** [comment] 2020-01-01 10:40
Here are the steps to recreate this problem:
1) Load up the solar app in your browser, get a graph showing your data.
2) turn off your wifi or unplug your ethernet
3) click on one of the date ranges such as "3h", "1d" etc (or wait for data to refresh).
4) You'll see the error appear.

**Comment by thedumbterminal** [comment] 2020-01-06 00:01
@glynhudson Could you take a look at the PR linked above, thanks.

**Comment by thedumbterminal** [comment] 2020-01-06 23:10
@emrysr hi any chance you could take a look at the above PR?

**Comment by emrysr** [comment] 2020-01-08 13:58
@thedumbterminal - I've tested it and all seems fine. not sure what the use case is when disconnected from the server? no new data will come through. But useful to clear the error. Thanks.

here's the error message I saw before testing the pull request:
![delwedd](https://user-images.githubusercontent.com/1466013/71983469-c690af80-321e-11ea-8481-c2b18d554001.png)

**Comment by thedumbterminal** [comment] 2020-01-09 19:19
@emrysr not so much a use case but i'm running a raspberry pi with a touch screen on the wall which constantly shows the solar app via chromium in kiosk mode.

The problem occurs when the pi loses wifi connection (i think it is on the edge of the router's range). if the solar (or any) app tries to refresh its data when the pi has got disconnected temporarily then the above error message pops up, which blocks other javascript from running and someone may need to click through a number of popups (depending on the duration of the wifi outage) to get the solar app to refresh its data again.

Ideally I would have better wifi, but I don't think that a popup should appear on these issues either.

Thanks for making an amazing product!

**Closed** 2020-01-22 15:07 UTC
Labels: bug
